name: Modify and Verify Package Name

on: workflow_dispatch

jobs:
  modify-package-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Display original package.json name
        run: cat package.json | jq '.displayName'

      - name: Modify package.json name
        run: jq '.displayName = "ArConnect BETA"' package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Display modified package.json name
        run: cat package.json | jq '.displayName'
